apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::028695239991:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::028695239991:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Z13FA1VLB24M
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-12T08:17:04Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2021-08-12T08:17:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1404"
  uid: 5750688b-a97a-45ce-a2d0-50d40d65520d
